In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Display all columns
pd.set_option('display.max_columns', None)

Matplotlib is building the font cache; this may take a moment.

In [4]:
# Load the dataset

df = pd.read_csv("../YouTube_Video.csv")

In [5]:
df.head()

,post_id,upload_date,video_duration_min,avg_view_duration_sec,avg_view_percentage,subscribers_gained,traffic_source,ctr_percentage,impressions,likes,comments,shares,total_watch_time_hours,content_category
0,YT0000001,2025-04-08 08:32:24.541512,45.55,2422,88.62,564,Shorts Feed,28.70,1975899,88186,1055,63,1329340.94,Sports
1,YT0000002,2025-06-30 08:32:24.541512,59.12,562,15.84,523,Notifications,25.67,1552915,69884,5883,131,242427.29,Vlog
2,YT0000003,2025-06-26 08:32:24.541512,40.06,2369,98.56,628,External,10.13,90886,37931,3746,2555,59808.04,News
3,YT0000004,2025-03-04 08:32:24.541512,42.54,2097,82.16,239,External,25.00,999294,38861,1575,900,582088.76,Education
4,YT0000005,2025-10-25 08:32:24.541512,31.40,1424,75.58,138,Shorts Feed,23.49,1656171,57043,3150,1452,655107.64,Sports

In [6]:
df.shape

(29999, 14)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   post_id                 29999 non-null  str
 1   upload_date             29999 non-null  str
 2   video_duration_min      29999 non-null  float64
 3   avg_view_duration_sec   29999 non-null  int64
 4   avg_view_percentage     29999 non-null  float64
 5   subscribers_gained      29999 non-null  int64
 6   traffic_source          29999 non-null  str
 7   ctr_percentage          29999 non-null  float64
 8   impressions             29999 non-null  int64
 9   likes                   29999 non-null  int64
 10  comments                29999 non-null  int64
 11  shares                  29999 non-null  int64
 12  total_watch_time_hours  29999 non-null  float64
 13  content_category        29999 non-null  str
dtypes: float64(4), int64(6), str(4)
memory usage: 3.2 MB

In [8]:
# Display summary statistics of numerical columns

df.describe()

,video_duration_min,avg_view_duration_sec,avg_view_percentage,subscribers_gained,ctr_percentage,impressions,likes,comments,shares,total_watch_time_hours
count,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,2.999900e+04,29999.000000,29999.000000,29999.000000,2.999900e+04
mean,30.481357,918.484049,50.243980,352.227908,15.071528,1.005525e+06,50031.577686,4010.686956,1503.401347,2.564022e+05
std,17.083015,791.358713,28.645129,202.444530,8.654916,5.770686e+05,28824.914627,2310.431564,866.938084,2.947842e+05
min,1.000000,5.000000,0.150000,0.000000,0.100000,1.060000e+02,1.000000,0.000000,0.000000,5.330000e+00
25%,15.605000,263.000000,25.585000,177.000000,7.500000,5.105605e+05,24983.500000,2019.500000,751.000000,4.435740e+04
50%,30.210000,696.000000,50.170000,354.000000,15.080000,1.004931e+06,50104.000000,4013.000000,1509.000000,1.436324e+05
75%,45.290000,1397.000000,74.810000,527.000000,22.560000,1.503998e+06,74905.000000,6018.500000,2251.000000,3.655550e+05
max,60.000000,3571.000000,100.000000,700.000000,30.000000,1.999924e+06,99989.000000,8000.000000,3000.000000,1.895754e+06

In [9]:
# Check for missing values in each column

df.isnull().sum()

post_id                   0
upload_date               0
video_duration_min        0
avg_view_duration_sec     0
avg_view_percentage       0
subscribers_gained        0
traffic_source            0
ctr_percentage            0
impressions               0
likes                     0
comments                  0
shares                    0
total_watch_time_hours    0
content_category          0
dtype: int64

In [10]:
# Count total missing values

total_missing = df.isnull().sum().sum()

print("Total Missing Values:", total_missing)

Total Missing Values: 0

In [11]:
# Check duplicate rows

duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [12]:
# Remove duplicate rows

df = df.drop_duplicates()

In [13]:
print("Duplicate Rows After Cleaning:", df.duplicated().sum())

Duplicate Rows After Cleaning: 0

In [14]:

# Remove unnecessary columns

df = df.drop(columns=["post_id", "upload_date"])

In [15]:
df.columns

Index(['video_duration_min', 'avg_view_duration_sec', 'avg_view_percentage',
       'subscribers_gained', 'traffic_source', 'ctr_percentage', 'impressions',
       'likes', 'comments', 'shares', 'total_watch_time_hours',
       'content_category'],
      dtype='str')

In [18]:
# Save the cleaned dataset

df.to_csv("../processed/cleaned_youtube_data.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!