In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
train_path = "../data/train.csv"
test_path = "../data/test.csv"

In [3]:
train_df = pd.read_csv(train_path)
test_df = pd.read_csv(test_path)

print("Train dataset shape:", train_df.shape)
print("Test dataset shape:", test_df.shape)

Train dataset shape: (650000, 2)
Test dataset shape: (50000, 2)

In [4]:
train_df.head()

   class_index                                        review_text
0            5  dr. goldberg offers everything i look for in a...
1            2  Unfortunately, the frustration of being Dr. Go...
2            4  Been going to Dr. Goldberg for over 10 years. ...
3            4  Got a letter in the mail last week that said D...
4            1  I don't know what Dr. Goldberg was like before...

In [5]:
test_df.head()

   class_index                                        review_text
0            1  I got 'new' tires from them and within two wee...
1            1  Don't waste your time.  We had two different p...
2            1  All I can say is the worst! We were the only 2...
3            1  I have been to this restaurant twice and was d...
4            1  Food was NOT GOOD at all! My husband & I ate h...

In [6]:
print("Train columns:")
print(train_df.columns.tolist())

print("\nTest columns:")
print(test_df.columns.tolist())

Train columns:
['class_index', 'review_text']

Test columns:
['class_index', 'review_text']

In [7]:
print(train_df.dtypes)
print()
print(test_df.dtypes)

class_index    int64
review_text      str
dtype: object

class_index    int64
review_text      str
dtype: object

In [8]:
print("Missing values in train dataset:")
print(train_df.isnull().sum())

print("\nMissing values in test dataset:")
print(test_df.isnull().sum())

Missing values in train dataset:
class_index    0
review_text    0
dtype: int64

Missing values in test dataset:
class_index    0
review_text    0
dtype: int64

In [ ]:
print("Train class distribution:")
print(train_df["class_index"].value_counts().sort_index())

print("\nTest class distribution:")
print(test_df["class_index"].value_counts().sort_index())

Train class distribution:
class_index
1    130000
2    130000
3    130000
4    130000
5    130000
Name: count, dtype: int64

Test class distribution:
class_index
1    10000
2    10000
3    10000
4    10000
5    10000
Name: count, dtype: int64

In [10]:
df = pd.concat(
    [train_df, test_df],
    ignore_index=True
)

print("Combined dataset shape:", df.shape)

Combined dataset shape: (700000, 2)

In [11]:
class_distribution = (
    df["class_index"]
    .value_counts()
    .sort_index()
)

print(class_distribution)

class_index
1    140000
2    140000
3    140000
4    140000
5    140000
Name: count, dtype: int64

In [12]:
df_filtered = df[
    df["class_index"].isin([1, 3, 5])
].copy()

print("Shape after filtering:", df_filtered.shape)

Shape after filtering: (420000, 2)

In [13]:
sentiment_mapping = {
    1: "Negative",
    3: "Neutral",
    5: "Positive"
}

df_filtered["sentiment"] = df_filtered["class_index"].map(
    sentiment_mapping
)

df_filtered.head()

   class_index                                        review_text sentiment
0            5  dr. goldberg offers everything i look for in a...  Positive
4            1  I don't know what Dr. Goldberg was like before...  Negative
5            5  Top notch doctor in a top notch practice. Can'...  Positive
6            5  Dr. Eric Goldberg is a fantastic doctor who ha...  Positive
7            1  I'm writing this review to give you a heads up...  Negative

In [14]:
print(
    df_filtered["sentiment"]
    .value_counts()
)

sentiment
Positive    140000
Negative    140000
Neutral     140000
Name: count, dtype: int64

In [15]:
random_state = 42

negative_samples = df_filtered[
    df_filtered["sentiment"] == "Negative"
].sample(
    n=50000,
    random_state=random_state
)

neutral_samples = df_filtered[
    df_filtered["sentiment"] == "Neutral"
].sample(
    n=50000,
    random_state=random_state
)

positive_samples = df_filtered[
    df_filtered["sentiment"] == "Positive"
].sample(
    n=50000,
    random_state=random_state
)

In [16]:
balanced_df = pd.concat(
    [
        negative_samples,
        neutral_samples,
        positive_samples
    ],
    ignore_index=True
)

In [17]:
balanced_df = balanced_df.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [18]:
print("Final dataset shape:", balanced_df.shape)

Final dataset shape: (150000, 3)

In [19]:
print(
    balanced_df["sentiment"]
    .value_counts()
)

sentiment
Neutral     50000
Negative    50000
Positive    50000
Name: count, dtype: int64

In [20]:
print(
    balanced_df.isnull().sum()
)

class_index    0
review_text    0
sentiment      0
dtype: int64

In [21]:
os.makedirs("../data/processed", exist_ok=True)
output_path = "../data/processed/yelp_balanced_150k.csv"

balanced_df.to_csv(
    output_path,
    index=False
)

print("Balanced dataset saved successfully.")
print("Location:", output_path)

Balanced dataset saved successfully.
Location: ../data/processed/yelp_balanced_150k.csv